Full version branch
Theodore354/MOBILE-SKELETON-VERSION-2 pull request #2
Opened 2021-11-26 11:23 UTC by Theodore354

2021-11-26 15:49 UTC, Gambit142 reviewed
Hi @Theodore354 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have a pull request summary, kindly describe what you did in this branch as the pull request summary

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2021-11-26 16:44 UTC, sheylaPozo commented
# Required Changes ♻️ 
Hi dear student @Theodore354, 

**Good job so far!**
You still need to work on some issues to go to the next project, but you are almost there!

Good points 👍
You used proper GitHub Flow ✔️
Your linter checks are all passing ✔️
Your commit messages are descriptive ✔️

**Aspects to improve ♻️**
 Check the comments under the review.
**Optional suggestions**
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-26 16:58 UTC, sheylaPozo commented
# ♻ Required changes ♻

- While the project is almost complete, you still have some changes yet to do to get approved, as it is a mobile version, it has to match with the original Figma template, in your case template 3, in all the aspects (images in backgrounds included, and dimensions)

**Example :** 

Figma version        | Your Mobile version
-------------------- | ----------------------
![template](https://user-images.githubusercontent.com/54015740/143611626-d9b12056-432d-4d39-a57d-eebab05b17f9.png) |  ![Mobile](https://user-images.githubusercontent.com/54015740/143611846-7902cc6a-baa9-47d1-816e-92b51564eab8.png)

if we compare both versions, the Figma version at the 100% percent shows the icons of the social media, while yours in 100% doesn't show them, and this is due the dimensions you used on your CSS,  kindly change the dimensions to make it fit and look like in the template example, also you're missing one of the background images in the mobile version... 
### Recommendations :
![temp](https://user-images.githubusercontent.com/54015740/143612214-8c028c65-da0d-4c74-964b-72cbb865ec76.png) Kindly make sure to always check to have all the background images in your project when you go into the mobile version, I see you put the image there on the desktop size but we aren't reviewing desktop this time, only mobile, and it should be included there in your project.  

- [ ] If you have any doubts or questions make sure to leave them under the comment section..

![sticker](https://user-images.githubusercontent.com/54015740/143612613-93b40bc9-e646-4f7d-964a-7e5218ff2045.jpg)

2021-11-26 17:00 UTC, sheylaPozo commented
# ♻ Required changes ♻

- While the project is almost complete, you still have some changes yet to do to get approved, as it is a mobile version, it has to match with the original Figma template, in your case template 3, in all the aspects (images in backgrounds included, and dimensions)

**Example :** 

Figma version        | Your Mobile version
-------------------- | ----------------------
![template](https://user-images.githubusercontent.com/54015740/143611626-d9b12056-432d-4d39-a57d-eebab05b17f9.png) |  ![Mobile](https://user-images.githubusercontent.com/54015740/143611846-7902cc6a-baa9-47d1-816e-92b51564eab8.png)

if we compare both versions, the Figma version at the 100% percent shows the icons of the social media, while yours in 100% doesn't show them, and this is due to the dimensions you used on your CSS,  kindly change the dimensions to make it fit and look like in the template example, also you're missing one of the background images in the mobile version... 
### Recommendations :
![temp](https://user-images.githubusercontent.com/54015740/143612214-8c028c65-da0d-4c74-964b-72cbb865ec76.png) Kindly make sure to always check to have all the background images in your project when you go into the mobile version, I see you put the image there on the desktop size but we aren't reviewing desktop this time, only mobile, and it should be included there in your project.  

- [ ] If you have any doubts or questions make sure to leave them under the comment section..


![sticker](https://user-images.githubusercontent.com/54015740/143612855-de3253f4-512c-4b0f-8e07-90db184864ba.jpg)

2021-11-26 17:02 UTC, sheylaPozo commented
# ♻ Required changes ♻

- While the project is almost complete, you still have some changes yet to do to get approved, as it is a mobile version, it has to match with the original Figma template, in your case template 3, in all the aspects (images in backgrounds included, and dimensions)

### **Example :** 

Figma version        | Your Mobile version
-------------------- | ----------------------
![template](https://user-images.githubusercontent.com/54015740/143611626-d9b12056-432d-4d39-a57d-eebab05b17f9.png) |  ![Mobile](https://user-images.githubusercontent.com/54015740/143611846-7902cc6a-baa9-47d1-816e-92b51564eab8.png)

if we compare both versions, the Figma version at the 100% percent shows the icons of the social media, while yours in 100% doesn't show them, and this is due to the dimensions you used on your CSS,  kindly change the dimensions to make it fit and look like in the template example, also you're missing one of the background images in the mobile version... 
### Recommendations :

![temp](https://user-images.githubusercontent.com/54015740/143612214-8c028c65-da0d-4c74-964b-72cbb865ec76.png) 

- Kindly make sure to always check to have all the background images in your project when you go into the mobile version, I see you put the image there on the desktop size but we aren't reviewing desktop this time, only mobile, and it should be included there in your project.  
---

![sticker](https://user-images.githubusercontent.com/54015740/143612855-de3253f4-512c-4b0f-8e07-90db184864ba.jpg)

---
- [ ] If you have any doubts or questions make sure to leave them under the comment section..

2021-11-26 17:10 UTC, sheylaPozo requested changes

2021-11-26 17:10 UTC, sheylaPozo commented on index.html
>        </ul>
# ♻ Required changes ♻

- While the project is almost complete, you still have some changes yet to do to get approved, as it is a mobile version, it has to match with the original Figma template, in your case template 3, in all the aspects (images in backgrounds included, and dimensions)

### **Example :** 

Figma version        | Your Mobile version
-------------------- | ----------------------
![template](https://user-images.githubusercontent.com/54015740/143611626-d9b12056-432d-4d39-a57d-eebab05b17f9.png) |  ![Mobile](https://user-images.githubusercontent.com/54015740/143611846-7902cc6a-baa9-47d1-816e-92b51564eab8.png)

if we compare both versions, the Figma version at the 100% percent shows the icons of the social media, while yours in 100% doesn't show them, and this is due to the dimensions you used on your CSS,  kindly change the dimensions to make it fit and look like in the template example, also you're missing one of the background images in the mobile version... 
### Recommendations :

![temp](https://user-images.githubusercontent.com/54015740/143612214-8c028c65-da0d-4c74-964b-72cbb865ec76.png) 

- Kindly make sure to always check to have all the background images in your project when you go into the mobile version, I see you put the image there on the desktop size but we aren't reviewing desktop this time, only mobile, and it should be included there in your project.  
---

![sticker](https://user-images.githubusercontent.com/54015740/143612855-de3253f4-512c-4b0f-8e07-90db184864ba.jpg)

---
- [ ] If you have any doubts or questions make sure to leave them under the comment section..

2021-11-26 17:18 UTC, sheylaPozo commented
###  ♻ Required changes ♻
![readme](https://user-images.githubusercontent.com/54015740/143614236-9048ae05-9fbd-4e27-95a1-9e30db971981.png)
images.githubusercontent.com/54015740/143613927-96b7d6fe-a2db-452a-b1da-fa4266fdcaf0.png)

- Remember for a professional-looking readme file Microverse's request is to have all the links on the readme file be functional and direct us to the right page, in this case, your Mit license isn't linked to a valid link, I won't invalidate your project for that for this time since your project was already invalidated before but I kindly suggest to replace that link or remove it completely from the license part, also is all about presentation and there's an extra icon in the Authors part, that would look better if it was removed.
`![readme](https://user-images.githubusercontent.com/54015740/143614276-0caa3113-d8b7-4b34-9625-a20f9fcccce2.png)`
 ----

2021-11-26 17:34 UTC, sheylaPozo commented
## Optional Suggestions 
---

- [x]  Kindly try to be more descriptive on the PR for the reviewers to know what changes you made and what you worked on, always remember that's part of the requirements for presentation, also make sure to be more kind, polite and respectful in the  description of your PR, is a valid reason for project invalidation, I see that you have tried to make the effort to describe it and I understand not all know how to properly describe the project in a manner for everyone to understand the changes clearly and for it to look more proffesional  👍 💯 

Your PR description       |  Example of descriptive PR
-------------------------- | -----------------------------
![optional](https://user-images.githubusercontent.com/54015740/143615185-28da70ff-23ce-4da8-8fd0-419fad441723.png)
om/54015740/127129480-dfb12898-5429-4ff7-a67a-f4e3df0edc64.gif) | ![descriptive](https://user-images.githubusercontent.com/54015740/143615667-94f682ff-7c17-4db1-90dd-d38a284cb8f3.png)

![tenor](https://user-images.githubusercontent.

2021-11-26 17:36 UTC, sheylaPozo commented
## Optional Suggestions 📌📌
---

- [ ] Kindly try to be more descriptive on the PR for the reviewers to know what changes you made and what you worked on, always remember that's part of the requirements for presentation, also make sure to be more kind, polite, and respectful in the description of your PR, is a valid reason for project invalidation, I see that you have tried to make the effort to describe it and I understand not all know how to properly describe the project in a manner for everyone to understand the changes clearly and for it to look more professional  👍 💯 

Your PR description       |  Example of descriptive PR
-------------------------- | -----------------------------
![optional](https://user-images.githubusercontent.com/54015740/143615185-28da70ff-23ce-4da8-8fd0-419fad441723.png)
om/54015740/127129480-dfb12898-5429-4ff7-a67a-f4e3df0edc64.gif) | ![descriptive](https://user-images.githubusercontent.com/54015740/143615667-94f682ff-7c17-4db1-90dd-d38a284cb8f3.png)

![tenor](https://user-images.githubusercontent.)
---
That's all :) keep doing a good job, and happy coding 💪😎💯

2021-11-26 17:38 UTC, sheylaPozo commented
## Optional Suggestions 📌📌
---

- [ ] Kindly try to be more descriptive on the PR for the reviewers to know what changes you made and what you worked on, always remember that's part of the requirements for presentation, also make sure to be more kind, polite, and respectful in the description of your PR, is a valid reason for project invalidation, I see that you have tried to make the effort to describe it and I understand not all know how to properly describe the project in a manner for everyone to understand the changes clearly and for it to look more professional  👍 💯 

Your PR description       |  Example of descriptive PR
-------------------------- | -----------------------------
![optional](https://user-images.githubusercontent.com/54015740/143615185-28da70ff-23ce-4da8-8fd0-419fad441723.png)
om/54015740/127129480-dfb12898-5429-4ff7-a67a-f4e3df0edc64.gif) | ![descriptive](https://user-images.githubusercontent.com/54015740/143615667-94f682ff-7c17-4db1-90dd-d38a284cb8f3.png)

---

![digilah-digifun](https://user-images.githubusercontent.com/54015740/143616014-1fb84ad7-5deb-4db9-9294-c0e28567e6ca.gif)

`That's all :) keep doing a good job, and happy coding 💪😎💯`

2021-11-26 17:42 UTC, sheylaPozo commented
## Optional Suggestions 📌📌
---

- [ ] Kindly try to be more descriptive on the PR for the reviewers to know what changes you made and what you worked on, always remember that's part of the requirements for presentation, also make sure to be more kind, polite, and respectful in the description of your PR, is a valid reason for project invalidation, I see that you have tried to make the effort to describe it and I understand not all know how to properly describe the project in a manner for everyone to understand the changes clearly and for it to look more professional  👍 💯 

Your PR description       |  Example of descriptive PR
-------------------------- | -----------------------------
![optional](https://user-images.githubusercontent.com/54015740/143615185-28da70ff-23ce-4da8-8fd0-419fad441723.png)| ![descriptive](https://user-images.githubusercontent.com/54015740/143615667-94f682ff-7c17-4db1-90dd-d38a284cb8f3.png)

---

![digilah-digifun](https://user-images.githubusercontent.com/54015740/143616014-1fb84ad7-5deb-4db9-9294-c0e28567e6ca.gif)

`That's all :) keep doing a good job, and happy coding 💪😎💯`

2021-11-26 18:30 UTC, sheylaPozo commented
## Optional Suggestions 
---

- [ ] As best practices remember to add all the images into the "img" folder because it makes it look more professional.

![folder](https://user-images.githubusercontent.com/54015740/143619604-a5be9fe9-9384-4bd1-a60d-2d18dc733927.png)
![coding](https://user-images.githubusercontent.com/54015740/143619782-76a5258d-0a82-4cb3-b07a-645f6f9c1355.gif)
---
###  Happy coding 🎉😄

2021-11-27 17:12 UTC, andersonlebon approved these changes
### Hi @Theodore354 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

![nodding-yes](https://user-images.githubusercontent.com/65068771/143095390-344d1cb0-b853-4b91-8662-5d9049dc9e60.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- You  are following GitHub actions :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Your README file is now professional :heavy_check_mark: 

## Optional suggestions
- [ ] Kindly Check the comments under the review._
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-11-27 17:12 UTC, andersonlebon commented on index.html
> +    </section>
## [OPTIONAL]
- [ ] Kindly work on the `background` of the about section, this should have the same `background` as the template, Check dow here :point_down:

Your design | the template
---------------- | -----------------
![Screenshot from 2021-11-27 18-55-57](https://user-images.githubusercontent.com/65068771/143690380-868fea94-6578-4b9c-bda2-bd0de6a76560.png) | ![Screenshot from 2021-11-27 19-04-42](https://user-images.githubusercontent.com/65068771/143690445-e94bd6a7-d463-44d6-a5b1-ea426584b665.png)
 
### kindly make this change as **IMPORTANT** one

2021-11-27 17:33 UTC, Theodore354 commented on index.html
> +    </section>
okay

2021-11-27 17:33 UTC, merged