Form contact branch
Theodore354/MOBILE-SKELETON-VERSION-2 pull request #3
Opened 2021-12-02 19:29 UTC by Theodore354

2021-12-02 20:39 UTC, MrBrN197 requested changes
## Hi, @Theodore354  👋 

You've done a really nice job so far.
There are some issues that you still need to work on to go to the next project but you are almost there!
## To highlight 👏👏
- ✔ Really well-done design. 
- ✔ Professional README
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-02 20:39 UTC, MrBrN197 commented on index.html
> +    </form>
- [ ] Hi, You've done really well in this section's design. I, however, noticed that you have some padding around this `footer`  which is causing the background image in this section to not be aligned to the edge of the page. as per the Figma design please ensure that the background image is aligned perfectly to right.
## Your Design
![image](https://user-images.githubusercontent.com/18730106/144497548-ef9a0e09-27b9-4997-b1c2-093adc63f51c.png)

## Figma Design (notice the image is aligned to the right edge)
![image](https://user-images.githubusercontent.com/18730106/144498646-c06627fb-7c10-4d3f-bb08-60cc5733cb4b.png)

2021-12-02 20:39 UTC, MrBrN197 commented on index.html
> +      <button class="btn" type="submit">Get In Touch</button>
- [ ] Hi, Your design matches very well in terms of the static appearance. however, as part of the requirements, you are supposed to implement the page perfectly according to the Figma template. I notice you don't have the button interactions on your design. Please add this to the buttons on your page. You can use the `:active` & `:hover` CSS pseud-classes to implement this in CSS 
## Button Interaction states
![image](https://user-images.githubusercontent.com/18730106/144499109-df8f57ea-c367-450d-9eb9-5819042c0f06.png)

2021-12-03 11:20 UTC, ShoiraTa approved these changes
### **STATUS: APPROVED  ✔️** 
------
Hi @Theodore354 ,  

Your project is complete!  There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

<img src="https://www.serialminds.com/wp-content/uploads/2015/11/loser.gif" width="400" height="250" />

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-03 11:20 UTC, ShoiraTa commented on index.html
> +<head>
- [ ] [OPTIONAL] I strongly suggest to check the skills links, it looks like something went wrong 😉:

Multi-post section | Languages section
---------|---------
![image](https://user-images.githubusercontent.com/77038610/144593798-db266e7f-4a9e-4700-a67c-18a5521f1bee.png) | ![image](https://user-images.githubusercontent.com/77038610/144593851-906fb9f0-97d1-49b6-a667-74b7690f264e.png)

I marked it as optional, because this is not the requirement for this milestone, however on the next milestone this will be `required` change

2021-12-03 11:34 UTC, merged